mirror: ""

corr_map:
fname: ""
save_path: ''
batch_size: 
openai_config:
  "name": ""
  "long_name": ""
  "embeddings": ""
  "batch_embed_fun": ""
bge_small_config:
  "name": ""
  "long_name": ""
  "embeddings": ""
  "batch_embed_fun": ""
bge_base_config:
  "name": ""
  "long_name": ""
  "embeddings": ""
  "batch_embed_fun": ""
bge_large_config:
  "name": ""
  "long_name": ""
  "embeddings": ""
  "batch_embed_fun": ""
